export enum ImageExtension {
  AVIF = 'avif',
  DCRAW = 'dcraw',
  DZ = 'dz',
  EXR = 'exr',
  FITS = 'fits',
  GIF = 'gif',
  HEIF = 'heif',
  INPUT = 'input',
  JPEG = 'jpeg',
  JPG = 'jpg',
  JP2 = 'jp2',
  JXL = 'jxl',
  MAGICK = 'magick',
  OPENSLIDE = 'openslide',
  PDF = 'pdf',
  PNG = 'png',
  PPM = 'ppm',
  RAD = 'rad',
  RAW = 'raw',
  SVG = 'svg',
  TIFF = 'tiff',
  TIF = 'tif',
  V = 'v',
  WEBP = 'webp',
}
